services:
  # Наше приложение (скрыто внутри, наружу не торчит)
  neko-app:
    build: .
    container_name: neko_finance
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_KEY=${GEMINI_KEY}
    volumes:
      - ./database.db:/app/database.db

  # Умный швейцар Caddy (торчит наружу и дает HTTPS)
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"   # Обычный вход
      - "443:443" # Защищенный вход (HTTPS)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Файл настройки
      - caddy_data:/data # Здесь он будет хранить сертификаты
      - caddy_config:/config
    depends_on:
      - neko-app

volumes:
  caddy_data:
  caddy_config: